-- App authentication schema (email/password + opaque sessions).
-- Idempotent — safe to re-run via db:init / ensureAuthSchema.

CREATE TABLE IF NOT EXISTS app_user (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email TEXT NOT NULL,
  email_normalized TEXT NOT NULL,
  password_hash TEXT NOT NULL,
  display_name TEXT,
  role TEXT NOT NULL DEFAULT 'user'
    CHECK (role IN ('user', 'admin')),
  plan TEXT NOT NULL DEFAULT 'free'
    CHECK (plan IN ('free', 'premium')),
  email_verified_at TIMESTAMPTZ,
  -- Future Stripe / billing fields (nullable until payments are wired)
  stripe_customer_id TEXT,
  stripe_subscription_id TEXT,
  subscription_status TEXT,
  subscription_current_period_start TIMESTAMPTZ,
  subscription_current_period_end TIMESTAMPTZ,
  subscription_cancel_at_period_end BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT app_user_email_normalized_unique UNIQUE (email_normalized)
);

-- Additive migrations for existing installs
ALTER TABLE app_user ADD COLUMN IF NOT EXISTS display_name TEXT;
ALTER TABLE app_user ADD COLUMN IF NOT EXISTS role TEXT;
UPDATE app_user SET role = 'user' WHERE role IS NULL;
ALTER TABLE app_user ALTER COLUMN role SET DEFAULT 'user';
-- Best-effort CHECK (ignore if already present / unsupported)
DO $$ BEGIN
  ALTER TABLE app_user ADD CONSTRAINT app_user_role_check CHECK (role IN ('user', 'admin'));
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

CREATE INDEX IF NOT EXISTS idx_app_user_plan ON app_user (plan);
CREATE INDEX IF NOT EXISTS idx_app_user_stripe_customer
  ON app_user (stripe_customer_id)
  WHERE stripe_customer_id IS NOT NULL;

CREATE TABLE IF NOT EXISTS app_session (
  id TEXT PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES app_user (id) ON DELETE CASCADE,
  expires_at TIMESTAMPTZ NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  last_seen_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  user_agent TEXT,
  ip TEXT
);

CREATE INDEX IF NOT EXISTS idx_app_session_user ON app_session (user_id);
CREATE INDEX IF NOT EXISTS idx_app_session_expires ON app_session (expires_at);

CREATE TABLE IF NOT EXISTS app_auth_token (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES app_user (id) ON DELETE CASCADE,
  purpose TEXT NOT NULL CHECK (purpose IN ('email_verify', 'password_reset')),
  token_hash TEXT NOT NULL UNIQUE,
  expires_at TIMESTAMPTZ NOT NULL,
  used_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_app_auth_token_user_purpose
  ON app_auth_token (user_id, purpose);
