-- Congressional member registry (party and identity enrichment for PTR trades).
-- Populated by the politician scraper enrichment step; not raw transaction storage.

CREATE TABLE IF NOT EXISTS politicians (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  politician_key VARCHAR(128) NOT NULL,
  bioguide_id VARCHAR(16),
  name TEXT NOT NULL,
  chamber VARCHAR(16) NOT NULL CHECK (chamber IN ('house', 'senate')),
  state CHAR(2),
  district VARCHAR(8),
  party VARCHAR(64),
  party_source VARCHAR(256),
  party_last_updated DATE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (politician_key, chamber)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_politicians_bioguide
  ON politicians (bioguide_id)
  WHERE bioguide_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_politicians_chamber_state
  ON politicians (chamber, state);

CREATE INDEX IF NOT EXISTS idx_politicians_party
  ON politicians (party);
