-- Stock directory + classification (SIC → sector / industry)
-- Sourced from the SEC Company Tickers dataset and SEC company submissions.
-- Run via: npm run db:init  (and refreshed via: npm run import:stocks)

CREATE TABLE IF NOT EXISTS stocks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  ticker VARCHAR(16) PRIMARY KEY,
  company_name TEXT,
  sector VARCHAR(128),
  industry VARCHAR(256),
  sic VARCHAR(8),
  sic_description TEXT,
  cik CHAR(10),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Backfill columns on pre-existing installations (idempotent).
ALTER TABLE stocks ADD COLUMN IF NOT EXISTS id BIGINT GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE stocks ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT NOW();

CREATE INDEX IF NOT EXISTS idx_stocks_sector ON stocks (sector);
CREATE INDEX IF NOT EXISTS idx_stocks_industry ON stocks (industry);
CREATE INDEX IF NOT EXISTS idx_stocks_sic ON stocks (sic);

-- Search indexes: case-insensitive exact/prefix lookups on ticker and company name.
CREATE INDEX IF NOT EXISTS idx_stocks_ticker_upper ON stocks (UPPER(ticker));
CREATE INDEX IF NOT EXISTS idx_stocks_company_name_lower ON stocks (LOWER(company_name));
